#!/bin/bash
# sbt-build.sh

set -euo pipefail
shopt -s inherit_errexit

sbt-build () {
        if [[ ! -e cabal.project ]]; then
            echo "Could not find 'cabal.project' file in current directory $(pwd)" >&2
            exit 1
        fi
        
        cabal new-build --enable-tests
        
	ghc_version=$(ghc --version | sed -n 's/.*version \([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/p')
        version=$(sed -n 's/^version:\s\+\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/p' sharad-backend.cabal)
	build_dir="dist-newstyle/build/x86_64-linux/ghc-$ghc_version/sharad-backend-$version"
        build_dir_backend_exe="$build_dir/x/sharad-backend/build/sharad-backend"
        exe_path="$build_dir_backend_exe/sharad-backend"
        
        if [[ ! -e $exe_path ]]; then
                echo "Could not find built executable at path: $exe_path" >&2
                exit 1
        fi
        
        echo "$exe_path"
}

