#!/bin/bash
# sbt-test.sh

sbt-test() {
        cabal new-run sharad-backend:sharad-unit-tests --run-tests
}

sbt-integration-test() {
        cabal new-run sharad-backend:sharad-integration-tests --run-tests
}
